### ISSUE TITLE
一些参数填写

### ISSUE THREAD

**Issue by andi911** [viakiba/ss-ios#2]
vpnInfo.serverAddress = @"";
        vpnInfo.remoteID = @"";
        vpnInfo.username = @"";
        vpnInfo.password = @"";
        vpnInfo.sharedSecret = @"";
请教一下，第一个填写服务器地址，第二个填什么，第三个username 是不是可以随便写， 第四个填写的是什么密码，用shadowsocks Mac客户端我连接成功了，第三个密码是填写shadowsocks Mac客户端 的密码吗？第4个 填写aes-256-cfb？

**Comment by viakiba** [comment]
不知道，很抱歉
